### ISSUE TITLE
ios 设备 蒙层无法触发点击事件的解决办法

### ISSUE THREAD

**Issue by fisker** [fisker/blog#7]
解决方法很简单， 加一行css

```css
.backdrop {
  cursor: pointer;
}
```

[codepen](https://codepen.io/lionkay/pen/mBOQew)
